#!/usr/bin/env bash
# Usage: orc status
# Summary: Shows running apps
# Help: Lists running unicorn apps!

source $_ORC_ROOT/share/orc/common.sh

command="$1"
case "$command" in
"docker" )
  $DOCKER ps -f name=orc
  ;;
"--short" )
  #shellcheck disable=SC2009
  ps -efa|grep 'unicorn master'|grep -v grep|awk -F'/tmp/unicorn.' '{print $2}'|awk -F. '{print $1}'
  exit 0
  ;;
* )
  pid_lines=$(ps auwx | grep "unicorn master" | grep -v grep)
  OLDIFS=$IFS
  IFS=$'\n'
  for line in $pid_lines
  do
    name=$(echo "$line"|awk -F'/tmp/unicorn.' '{print $2}'|awk -F. '{print $1}')
    pid=$(echo "$line"|awk '{print $2}')
    echo "$name: $pid"
  done
  IFS=$OLDIFS
  ;;
esac
