#!/usr/bin/env bash
# Usage: orc add /path/to/app [ alias ]
# Summary: Links an app into orc
# Help: Creates a link from the app into the orc directory

if [ $# -gt 1 ]; then
  appname=$2
elif [ -d "$1" ]; then
  appname=$(basename "$1")
else
  echo "Whoops! Not a real app"
  exit
fi

if [ -L "$ORC_APPS/$appname" ]; then
  echo "$appname already exists"
  exit
else
  if [ ! -e $ORC_APPS ]; then
    mkdir $ORC_APPS
  fi
  ln -s "$1" "$ORC_APPS/$appname"
  # Regenerate SSL cert with new apps and recreate web docker container
  orc-ssl regenerate-cert
fi
