#!/usr/bin/env bash
# Usage: orc stop <app> | orc stop all
# Summary: Stops running apps
# Help: Stops the given <app> or all apps if given 'all'

# Provide orc completions
if [ "$1" == "--complete" ]; then
  echo 'all'
  exec orc-status --short
fi

stop_app(){
  echo "Stopping $1"
  pkill -f "/tmp/unicorn.$1.sock"
}

case "$1" in
  all)
    for app in $(orc status --short)
    do
      stop_app "$app"
    done
    exit $?
    ;;
  *)
    stop_app "$1"
    ;;
esac
